"""마스코트 상점 — item_grants + 활성 마스코트 + 테마 가격 시드 (docs/specs/mascot-shop.md)

Revision ID: 3d4c34e2c8d9
Revises: 93ad7a71415a
Create Date: 2026-08-11
"""

from alembic import op

revision = "3d4c34e2c8d9"
down_revision = "93ad7a71415a"
branch_labels = None
depends_on = None

# XP 상점이 비어 있던 원인 = 가격 미입력 (2026-08-11 보고 — theme_settings 0행).
# 기본 가격 시드: 일일 획득량(활성 ~500XP) 기준 층위화. 백오피스가 이미 입력한
# 가격은 덮지 않는다 (price_xp IS NULL 일 때만 갱신).
THEME_PRICES = {
    "candy": 500,
    "lego": 500,
    "school": 800,
    "academy": 800,
    "ocean": 1200,
    "excel": 1200,
    "cat": 2000,
}


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE item_grants (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            item_key VARCHAR(64) NOT NULL,
            note TEXT,
            created_at timestamptz NOT NULL DEFAULT now(),
            CONSTRAINT uq_item_grants_user_key UNIQUE (user_id, item_key)
        )
        """
    )
    op.execute("CREATE INDEX ix_item_grants_user_id ON item_grants (user_id)")
    op.execute("ALTER TABLE user_settings ADD COLUMN mascot_key TEXT")
    for key, price in THEME_PRICES.items():
        op.execute(
            f"""
            INSERT INTO theme_settings (theme_key, access, price_xp)
            VALUES ('{key}', 'restricted', {price})
            ON CONFLICT (theme_key)
            DO UPDATE SET price_xp = EXCLUDED.price_xp
            WHERE theme_settings.price_xp IS NULL
            """
        )


def downgrade() -> None:
    op.execute("ALTER TABLE user_settings DROP COLUMN mascot_key")
    op.execute("DROP TABLE item_grants")
