"""사용 이벤트 원장 (P1-D 관측 격차 해소 — docs/specs/usage-events.md)

Revision ID: 93ad7a71415a
Revises: 9c4e06b9f79e
Create Date: 2026-08-10
"""

from alembic import op

revision = "93ad7a71415a"
down_revision = "9c4e06b9f79e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE usage_events (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            kind TEXT NOT NULL,
            meta JSONB NOT NULL DEFAULT '{}',
            created_at timestamptz NOT NULL DEFAULT now()
        )
        """
    )
    op.execute("CREATE INDEX ix_usage_events_user_id ON usage_events (user_id)")
    op.execute("CREATE INDEX ix_usage_kind_time ON usage_events (kind, created_at)")


def downgrade() -> None:
    op.execute("DROP TABLE usage_events")
