"""리스닝 빙고 대전 기록 (docs/specs/listening-bingo.md)

Revision ID: 9c4e06b9f79e
Revises: 9a3c7d21e4b8
Create Date: 2026-08-10
"""

from alembic import op

revision = "9c4e06b9f79e"
down_revision = "9a3c7d21e4b8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE bingo_matches (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            mode TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'waiting',
            player1_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
            player2_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
            winner_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
            stats JSONB NOT NULL DEFAULT '{}',
            ended_at timestamptz,
            created_at timestamptz NOT NULL DEFAULT now(),
            CONSTRAINT ck_bingo_mode CHECK (mode IN ('solo','room')),
            CONSTRAINT ck_bingo_status CHECK (status IN ('waiting','playing','finished','aborted'))
        )
        """
    )
    op.execute("CREATE INDEX ix_bingo_p1 ON bingo_matches (player1_id)")
    op.execute("CREATE INDEX ix_bingo_p2 ON bingo_matches (player2_id)")
    op.execute("CREATE INDEX ix_bingo_status_ended ON bingo_matches (status, ended_at)")


def downgrade() -> None:
    op.execute("DROP TABLE bingo_matches")
