"""DB 감사 — 누락 인덱스 보강 + 퀴즈 로얄 참가 기록 정규화 (2026-07-15)

Revision ID: b4c5d6e7f8a9
Revises: a3b4c5d6e7f8
Create Date: 2026-07-15

- PostgreSQL 은 FK 에 인덱스를 자동 생성하지 않는다 — 조회 패턴에 실제로
  쓰이는 컬럼만 선별 보강 (전부가 아니라 쿼리 근거 있는 것만).
- quiz_royale_players: players JSONB 파이썬 풀스캔(매 페이지뷰 O(전체 매치))을
  인덱스 집계로 대체. 기존 finished 매치를 백필.
"""

from alembic import op

revision = "b4c5d6e7f8a9"
down_revision = "a3b4c5d6e7f8"
branch_labels = None
depends_on = None

INDEXES = (
    # 가시성 서브쿼리(모든 큐/통계 쿼리에 포함)의 조인 키
    ("ix_occurrences_content", "item_occurrences", "(content_id)"),
    # rate_last_review 의 직전 로그 조회
    ("ix_logs_card", "review_logs", "(card_id)"),
    # 게임 전적/최고기록/주간 리더보드
    ("ix_matches_p1", "game_matches", "(player1_id)"),
    ("ix_matches_p2", "game_matches", "(player2_id)"),
    ("ix_matches_winner", "game_matches", "(winner_id)"),
    ("ix_matches_status_ended", "game_matches", "(status, ended_at)"),
    ("ix_typing_p1", "typing_races", "(player1_id)"),
    ("ix_typing_p2", "typing_races", "(player2_id)"),
    ("ix_typing_status_ended", "typing_races", "(status, ended_at)"),
    ("ix_qr_matches_status_ended", "quiz_royale_matches", "(status, ended_at)"),
    # 친구 목록 — uq(requester,addressee) 는 requester 쪽만 커버
    ("ix_friendships_addressee", "friendships", "(addressee_id)"),
)


def upgrade() -> None:
    for name, table, cols in INDEXES:
        op.execute(f"CREATE INDEX IF NOT EXISTS {name} ON {table} {cols}")

    op.execute(
        """
        CREATE TABLE quiz_royale_players (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            match_id BIGINT NOT NULL REFERENCES quiz_royale_matches(id) ON DELETE CASCADE,
            user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            score INT NOT NULL DEFAULT 0,
            rank SMALLINT,
            created_at timestamptz NOT NULL DEFAULT now()
        )
        """
    )
    op.execute("CREATE INDEX ix_quiz_royale_players_match_id ON quiz_royale_players (match_id)")
    op.execute("CREATE INDEX ix_quiz_royale_players_user_id ON quiz_royale_players (user_id)")
    # 백필 — 기존 finished 매치의 JSONB 스냅샷에서 유저 행만 (봇 user_id null 제외)
    op.execute(
        """
        INSERT INTO quiz_royale_players (match_id, user_id, score, rank, created_at)
        SELECT m.id,
               (p->>'user_id')::bigint,
               COALESCE((p->>'score')::int, 0),
               (p->>'rank')::smallint,
               COALESCE(m.ended_at, m.created_at)
        FROM quiz_royale_matches m,
             jsonb_array_elements(m.players->'players') AS p
        WHERE m.status = 'finished'
          AND p->>'user_id' IS NOT NULL
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE quiz_royale_players")
    for name, _table, _cols in INDEXES:
        op.execute(f"DROP INDEX IF EXISTS {name}")
