"""스피드 퀴즈 로얄 매치 기록 — 최대 4인 (docs/proposal/quiz-royale.md)

Revision ID: b8c9d0e1f2a3
Revises: a7b8c9d0e1f2
Create Date: 2026-07-14
"""

from alembic import op

revision = "b8c9d0e1f2a3"
down_revision = "a7b8c9d0e1f2"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE quiz_royale_matches (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            host_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
            mode TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'waiting',
            players JSONB NOT NULL DEFAULT '{}'::jsonb,
            ended_at timestamptz,
            created_at timestamptz NOT NULL DEFAULT now(),
            CONSTRAINT ck_qr_mode CHECK (mode IN ('solo','room')),
            CONSTRAINT ck_qr_status
                CHECK (status IN ('waiting','playing','finished','aborted'))
        )
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE quiz_royale_matches")
