"""영문 타자연습 기록 — 싱글/2인 대결 (docs/specs/typing-race.md)

Revision ID: d0e1f2a3b4c5
Revises: c9d0e1f2a3b4
Create Date: 2026-07-14
"""

from alembic import op

revision = "d0e1f2a3b4c5"
down_revision = "c9d0e1f2a3b4"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE typing_races (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            mode TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'waiting',
            player1_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
            player2_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
            winner_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
            p1_chars INTEGER NOT NULL DEFAULT 0,
            p2_chars INTEGER NOT NULL DEFAULT 0,
            stats JSONB NOT NULL DEFAULT '{}'::jsonb,
            ended_at timestamptz,
            created_at timestamptz NOT NULL DEFAULT now(),
            CONSTRAINT ck_typing_mode CHECK (mode IN ('solo','race')),
            CONSTRAINT ck_typing_status
                CHECK (status IN ('waiting','playing','finished','aborted'))
        )
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE typing_races")
