"""어순 조립 레이스 — scramble_races (docs/specs/scramble-race.md)

Revision ID: d6e7f8a9b0c1
Revises: c5d6e7f8a9b0
Create Date: 2026-07-15
"""

from alembic import op

revision = "d6e7f8a9b0c1"
down_revision = "c5d6e7f8a9b0"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE scramble_races (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            mode TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'waiting',
            player1_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
            player2_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
            winner_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
            p1_score INT NOT NULL DEFAULT 0,
            p2_score INT NOT NULL DEFAULT 0,
            stats JSONB NOT NULL DEFAULT '{}',
            ended_at timestamptz,
            created_at timestamptz NOT NULL DEFAULT now(),
            CONSTRAINT ck_scramble_mode CHECK (mode IN ('solo','race')),
            CONSTRAINT ck_scramble_status CHECK (status IN ('waiting','playing','finished','aborted'))
        )
        """
    )
    # 조회 인덱스 선제 생성 — 전적/주간 리더보드 (DB 감사 2026-07-15 원칙)
    op.execute("CREATE INDEX ix_scramble_p1 ON scramble_races (player1_id)")
    op.execute("CREATE INDEX ix_scramble_p2 ON scramble_races (player2_id)")
    op.execute("CREATE INDEX ix_scramble_status_ended ON scramble_races (status, ended_at)")


def downgrade() -> None:
    op.execute("DROP TABLE scramble_races")
