"""친구 관계 — 관전 진입용 (docs/specs/study-spectate.md)

Revision ID: e1f2a3b4c5d6
Revises: d0e1f2a3b4c5
Create Date: 2026-07-14
"""

from alembic import op

revision = "e1f2a3b4c5d6"
down_revision = "d0e1f2a3b4c5"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE friendships (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            requester_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            addressee_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            status TEXT NOT NULL DEFAULT 'pending',
            created_at timestamptz NOT NULL DEFAULT now(),
            CONSTRAINT uq_friend_pair UNIQUE (requester_id, addressee_id),
            CONSTRAINT ck_friend_status CHECK (status IN ('pending','accepted')),
            CONSTRAINT ck_friend_not_self CHECK (requester_id != addressee_id)
        )
        """
    )


def downgrade() -> None:
    op.execute("DROP TABLE friendships")
