"""init schema

Revision ID: e3f3fb706968
Revises: 
Create Date: 2026-07-11 13:46:46.091788

"""
from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'e3f3fb706968'
down_revision: str | Sequence[str] | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('learning_items',
    sa.Column('item_type', sa.Text(), nullable=False),
    sa.Column('en_text', sa.Text(), nullable=False),
    sa.Column('ko_text', sa.Text(), nullable=False),
    sa.Column('normalized_key', sa.Text(), nullable=False),
    sa.Column('hint_thinking', sa.Text(), nullable=True),
    sa.Column('pattern_template', sa.Text(), nullable=True),
    sa.Column('difficulty_hint', sa.Text(), server_default='intermediate', nullable=False),
    sa.Column('review_status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('extra', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("difficulty_hint IN ('basic','intermediate','advanced')", name='ck_items_difficulty'),
    sa.CheckConstraint("item_type IN ('word','idiom','pattern','sentence')", name='ck_items_type'),
    sa.CheckConstraint("review_status IN ('pending','approved','rejected')", name='ck_items_review_status'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_type', 'normalized_key', name='uq_items_type_key')
    )
    op.create_table('users',
    sa.Column('google_sub', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('avatar_url', sa.Text(), nullable=True),
    sa.Column('role', sa.Text(), server_default='learner', nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("role IN ('admin','learner')", name='ck_users_role'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('google_sub')
    )
    op.create_table('contents',
    sa.Column('source', sa.Text(), nullable=False),
    sa.Column('youtube_video_id', sa.Text(), nullable=True),
    sa.Column('url', sa.Text(), nullable=True),
    sa.Column('title', sa.Text(), nullable=False),
    sa.Column('title_ko', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_by', sa.BigInteger(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("source IN ('youtube','manual')", name='ck_contents_source'),
    sa.CheckConstraint("status IN ('pending','extracting','ready','failed')", name='ck_contents_status'),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('youtube_video_id')
    )
    op.create_table('game_matches',
    sa.Column('mode', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='waiting', nullable=False),
    sa.Column('room_code', sa.Text(), nullable=True),
    sa.Column('player1_id', sa.BigInteger(), nullable=False),
    sa.Column('player2_id', sa.BigInteger(), nullable=True),
    sa.Column('bot_level', sa.SmallInteger(), nullable=True),
    sa.Column('winner_id', sa.BigInteger(), nullable=True),
    sa.Column('p1_score', sa.Integer(), server_default='0', nullable=False),
    sa.Column('p2_score', sa.Integer(), server_default='0', nullable=False),
    sa.Column('stats', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ended_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("mode IN ('pvp','pve')", name='ck_matches_mode'),
    sa.CheckConstraint("status IN ('waiting','playing','finished','aborted')", name='ck_matches_status'),
    sa.ForeignKeyConstraint(['player1_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['player2_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['winner_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_cards',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('state', sa.Text(), server_default='new', nullable=False),
    sa.Column('due_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('stability', sa.Float(), nullable=True),
    sa.Column('difficulty', sa.Float(), nullable=True),
    sa.Column('reps', sa.Integer(), server_default='0', nullable=False),
    sa.Column('lapses', sa.Integer(), server_default='0', nullable=False),
    sa.Column('suspended', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('last_review_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("state IN ('new','learning','review','relearning')", name='ck_cards_state'),
    sa.ForeignKeyConstraint(['item_id'], ['learning_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'item_id', name='uq_cards_user_item')
    )
    op.create_index('idx_cards_due', 'review_cards', ['user_id', 'due_at'], unique=False, postgresql_where='NOT suspended')
    op.create_table('user_settings',
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('daily_new_limit', sa.Integer(), server_default='20', nullable=False),
    sa.Column('daily_review_limit', sa.Integer(), server_default='200', nullable=False),
    sa.Column('desired_retention', sa.Float(), server_default='0.9', nullable=False),
    sa.Column('levels_enabled', sa.JSON().with_variant(postgresql.ARRAY(sa.Integer()), 'postgresql'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id')
    )
    op.create_table('extraction_jobs',
    sa.Column('content_id', sa.BigInteger(), nullable=False),
    sa.Column('step', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), server_default='pending', nullable=False),
    sa.Column('attempt', sa.Integer(), server_default='0', nullable=False),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=sa.Text()), 'postgresql'), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.CheckConstraint("status IN ('pending','running','done','failed')", name='ck_jobs_status'),
    sa.CheckConstraint("step IN ('metadata','transcript','translate','extract')", name='ck_jobs_step'),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review_logs',
    sa.Column('card_id', sa.BigInteger(), nullable=False),
    sa.Column('user_id', sa.BigInteger(), nullable=False),
    sa.Column('rating', sa.SmallInteger(), nullable=False),
    sa.Column('correct', sa.Boolean(), nullable=False),
    sa.Column('answer_text', sa.Text(), nullable=True),
    sa.Column('quiz_mode', sa.Text(), nullable=False),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('state_before', sa.Text(), nullable=False),
    sa.Column('scheduled_days', sa.Float(), nullable=True),
    sa.Column('elapsed_days', sa.Float(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['card_id'], ['review_cards.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_logs_user_time', 'review_logs', ['user_id', 'reviewed_at'], unique=False)
    op.create_table('transcript_segments',
    sa.Column('content_id', sa.BigInteger(), nullable=False),
    sa.Column('seq', sa.Integer(), nullable=False),
    sa.Column('start_ms', sa.Integer(), nullable=True),
    sa.Column('end_ms', sa.Integer(), nullable=True),
    sa.Column('en_text', sa.Text(), nullable=False),
    sa.Column('ko_text', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content_id', 'seq', name='uq_segments_content_seq')
    )
    op.create_table('item_occurrences',
    sa.Column('item_id', sa.BigInteger(), nullable=False),
    sa.Column('content_id', sa.BigInteger(), nullable=False),
    sa.Column('segment_id', sa.BigInteger(), nullable=True),
    sa.Column('context_en', sa.Text(), nullable=True),
    sa.Column('context_ko', sa.Text(), nullable=True),
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['contents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['item_id'], ['learning_items.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['segment_id'], ['transcript_segments.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('item_id', 'content_id', 'segment_id', name='uq_occurrences_item_content_segment')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('item_occurrences')
    op.drop_table('transcript_segments')
    op.drop_index('idx_logs_user_time', table_name='review_logs')
    op.drop_table('review_logs')
    op.drop_table('extraction_jobs')
    op.drop_table('user_settings')
    op.drop_index('idx_cards_due', table_name='review_cards', postgresql_where='NOT suspended')
    op.drop_table('review_cards')
    op.drop_table('game_matches')
    op.drop_table('contents')
    op.drop_table('users')
    op.drop_table('learning_items')
    # ### end Alembic commands ###
