"""받아쓰기 배틀 + 데일리 단어 퍼즐 (docs/specs/dictation-battle.md, daily-puzzle.md)

Revision ID: e7f8a9b0c1d2
Revises: d6e7f8a9b0c1
Create Date: 2026-07-15
"""

from alembic import op

revision = "e7f8a9b0c1d2"
down_revision = "d6e7f8a9b0c1"
branch_labels = None
depends_on = None


def upgrade() -> None:
    op.execute(
        """
        CREATE TABLE dictation_races (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            mode TEXT NOT NULL,
            status TEXT NOT NULL DEFAULT 'waiting',
            player1_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
            player2_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
            winner_id BIGINT REFERENCES users(id) ON DELETE SET NULL,
            p1_score INT NOT NULL DEFAULT 0,
            p2_score INT NOT NULL DEFAULT 0,
            stats JSONB NOT NULL DEFAULT '{}',
            ended_at timestamptz,
            created_at timestamptz NOT NULL DEFAULT now(),
            CONSTRAINT ck_dictation_mode CHECK (mode IN ('solo','race')),
            CONSTRAINT ck_dictation_status CHECK (status IN ('waiting','playing','finished','aborted'))
        )
        """
    )
    op.execute("CREATE INDEX ix_dictation_p1 ON dictation_races (player1_id)")
    op.execute("CREATE INDEX ix_dictation_p2 ON dictation_races (player2_id)")
    op.execute("CREATE INDEX ix_dictation_status_ended ON dictation_races (status, ended_at)")

    op.execute(
        """
        CREATE TABLE daily_puzzle_plays (
            id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
            user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE CASCADE,
            day DATE NOT NULL,
            answer TEXT NOT NULL DEFAULT '',
            guesses JSONB NOT NULL DEFAULT '[]',
            solved BOOLEAN NOT NULL DEFAULT false,
            created_at timestamptz NOT NULL DEFAULT now(),
            CONSTRAINT uq_puzzle_user_day UNIQUE (user_id, day)
        )
        """
    )
    op.execute("CREATE INDEX ix_daily_puzzle_plays_user_id ON daily_puzzle_plays (user_id)")


def downgrade() -> None:
    op.execute("DROP TABLE daily_puzzle_plays")
    op.execute("DROP TABLE dictation_races")
